version: '3.9'

services:
  config-service:
    image: ${DOCKER_REGISTRY-}config-service
    container_name: com.config-service
    build:
      context: ../config-service/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - backend
      
  eureka-service:
    image: ${DOCKER_REGISTRY-}eureka-service
    container_name: com.eureka-service
    build:
      context: ../eureka-service/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend
      
  gateway-service:
    image: ${DOCKER_REGISTRY-}gateway-service
    container_name: com.gateway-service
    build:
      context: ../gateway-service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
      
  customer-service:
    image: ${DOCKER_REGISTRY-}customer-service
    container_name: com.customer-service
    build:
      context: ../customer-service/
      dockerfile: Dockerfile
    depends_on:
      - eureka-service
    networks:
      - backend
      
  credit-service:
    image: ${DOCKER_REGISTRY-}credit-service
    container_name: com.credit-service
    build:
      context: ../credit-service/
      dockerfile: Dockerfile
    depends_on:
      - eureka-service
    networks:
      - backend
      
  account-service:
    image: ${DOCKER_REGISTRY-}account-service
    container_name: com.account-service
    build:
      context: ../account-service/
      dockerfile: Dockerfile
    depends_on:
      - eureka-service
    networks:
      - backend
      
networks:
    backend:


#networks:
# backend:
#    name: backend
#    driver: bridge